apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    cloud.googleapis.com/location: {{ .Values.region }}

spec:
  template:
    spec:
      containers:
        - image: {{ .Values.image }}
          ports:
            - name: http1
              containerPort: {{ .Values.port }}
          startupProbe:
            httpGet:
              path: /ping
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.port }}
