root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./bin/api"
  cmd = "make api"
  delay = 1000
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  log = "build-errors.log"
  post_cmd = ["sleep 0.25 && make openapi"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
