name: Build and Deploy Preview
run-name: CI - Pull Request
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.push_image.outputs.image_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Test
        run: make test
        working-directory: ./api

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: make image
        working-directory: ./api

      - name: Push docker image
        id: push_image
        run: |
          make push
          IMAGE_URL=$(cat image.txt)
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
        working-directory: ./api

  preview:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Setup Helm'
        uses: azure/setup-helm@v4.2.0

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - id: 'generate_service'
        name: 'Generate service.yaml and save to output'
        working-directory: ./infra/helm
        run: |
          echo 'service_yaml<<EOF' >> $GITHUB_OUTPUT
          cat service.yaml >> $GITHUB_OUTPUT
          echo 'EOF' $GITHUB_OUTPUT

      - id: 'deploy'
        name: Deploy Preview with Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          metadata: ${{ steps.generate_service.outputs.service_yaml }}
          image: 'gcr.io/cloudrun/hello'
          env_vars: |

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
