name: Build and Deploy Preview
run-name: CI - Pull Request
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Test
        run: make test

        working-directory: ./api

  build:
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.push_image.outputs.image_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: make image
        working-directory: ./api

      - name: Push docker image
        id: push_image
        run: |
          make push
          IMAGE_URL=$(cat image.txt)
          echo "image_url=$IMAGE_URL" >> $GITHUB_OUTPUT
        working-directory: ./api

  preview:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Setup Helm'
        uses: azure/setup-helm@v4.2.0

      - id: 'generate_service'
        name: 'Generate service.yaml and save to output'
        working-directory: ./infra/helm
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |-
          echo "happened-$BRANCH_NAME"
          helm template cloudrun \
            --set name="happened-$BRANCH_NAME" \
            --set image=${{ needs.build.outputs.image_url }} \
            > service.yaml

          echo 'service_yaml<<EOF' >> $GITHUB_OUTPUT
          cat service.yaml >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

          cat service.yaml

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - id: 'deploy'
        name: Deploy Preview with Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          metadata: |-
            ${{ steps.generate_service.outputs.service_yaml }}
        #   env_vars: |
        #     DB_HOST= ${{ github.secrets.DB_HOST }}
        #     DB_USER= ${{ github.secrets.DB_USER }}
        #     DB_PASS= ${{ github.secrets.DB_PASS }}
        #     DB_NAME= ${{ github.secrets.DB_NAME }}
        #     DB_PORT= ${{ github.secrets.DB_PORT }}
        #     CLERK_SECRET_KEY= ${{ github.secrets.CLERK_SECRET_KEY }}

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
