name: Pull Request Closed or Branch Deleted

# Delete the preview deployment

on:
  pull_request:
    types:
      - closed # Trigger when a pull request is closed (whether merged or not)
  delete:

jobs:
  delete_branch_preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: Handle pull request closed or branch deleted
        working-directory: infra/helm
        run: ./delete.sh
